<template>
  <div>
    <section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">用领养代替购买</span><h1>为它找到家，<br><em>也让家更完整</em></h1><p>真实发布、充分沟通、认真审核。每一只等待中的小生命，都值得一次温柔而负责的相遇。</p><div class="hero-actions"><el-button type="primary" size="large" round @click="goPets">开始寻找萌宠</el-button><el-button size="large" round @click="$router.push('/publish')">发布寄养信息</el-button></div><div class="hero-stats"><div><strong>5</strong><span>宠物大类</span></div><div><strong>27</strong><span>细分品种</span></div><div><strong>全程</strong><span>沟通可追溯</span></div></div></div><div class="hero-visual"><div class="blob"></div><img src="/api/files/buoumao.jpg" alt="等待领养的萌宠" @error="imageFallback"><span class="float-note note-one">♡ 健康信息透明</span><span class="float-note note-two">⌂ 找到安心新家</span></div></div></section>
    <section class="section category-section"><div class="container"><div class="section-heading"><div><span class="eyebrow">按类别探索</span><h2>遇见你喜欢的伙伴</h2></div><router-link to="/pets">查看全部 <i class="el-icon-right" /></router-link></div><div class="category-grid"><button v-for="item in categories" :key="item.id" class="category-card" @click="goCategory(item.id)"><div class="category-image"><img :src="item.image" :alt="item.name" @error="imageFallback"></div><strong>{{ item.name }}</strong><small>{{ item.children.length }} 个细分类</small></button></div></div></section>
    <section class="section hot-section"><div class="container"><div class="section-heading"><div><span class="eyebrow">正在等待</span><h2>热门萌宠</h2></div><router-link to="/pets">发现更多 <i class="el-icon-right" /></router-link></div><div class="pet-grid"><PetCard v-for="pet in pets" :key="pet.id" :pet="pet" /></div></div></section>
    <section class="section steps-section"><div class="container"><div class="section-heading centered"><div><span class="eyebrow">领养流程</span><h2>认真选择，安心相伴</h2></div></div><div class="steps"><div v-for="(step,index) in steps" :key="step.title" class="step"><span>{{ index + 1 }}</span><i :class="step.icon" /><h3>{{ step.title }}</h3><p>{{ step.text }}</p></div></div></div></section>
  </div>
</template>
<script>
import { categoryApi, petApi } from '../api'; import PetCard from '../components/PetCard.vue'; import { imageFallback } from '../utils/format'
const categoryImages = { 1: '/api/files/buoumao.jpg', 2: '/api/files/jinmao.jpg', 3: '/api/files/cangshu.png', 4: '/api/files/tuzi.png', 5: '/api/files/niao.png' }
export default { components: { PetCard }, data: () => ({ categories: [], pets: [], steps: [{ title:'浏览筛选',text:'按类别和品种找到合适的伙伴',icon:'el-icon-search'},{title:'在线沟通',text:'和发布人充分了解健康与习惯',icon:'el-icon-chat-dot-round'},{title:'提交申请',text:'认真填写领养理由和居住条件',icon:'el-icon-document-checked'},{title:'等待审核',text:'双方确认后开启长久陪伴',icon:'el-icon-house' }] }), async created () { const tree = await categoryApi.tree(); this.categories = tree.filter(item => categoryImages[item.id]).map(item => ({ ...item, image: categoryImages[item.id] })); const data = await petApi.list({ status:'AVAILABLE', page:1, pageSize:8 }); this.pets = data.records }, methods: { imageFallback, goPets () { this.$router.push('/pets') }, goCategory (id) { this.$router.push(`/pets?categoryId=${id}`) } } }
</script>
