<template>
  <div class="page-bg detail-page" v-loading="loading"><div v-if="pet" class="container"><el-breadcrumb separator-class="el-icon-arrow-right"><el-breadcrumb-item :to="{path:'/pets'}">寻找萌宠</el-breadcrumb-item><el-breadcrumb-item>{{ pet.categoryName }}</el-breadcrumb-item><el-breadcrumb-item>{{ pet.name }}</el-breadcrumb-item></el-breadcrumb><div class="detail-card"><section class="gallery"><el-image class="main-image" :src="activeImage" :preview-src-list="pet.images" fit="cover" @error="imageFallback" /><div class="thumbs"><button v-for="url in pet.images" :key="url" :class="{active:url===activeImage}" @click="activeImage=url"><img :src="url" @error="imageFallback"></button></div></section><section class="detail-info"><div class="title-line"><div><el-tag :type="status.type" effect="dark" size="small">{{ status.text }}</el-tag><h1>{{ pet.name }}</h1><p>{{ pet.subcategoryName }} · {{ pet.breed }}</p></div><button class="favorite" aria-label="收藏"><i class="el-icon-star-off" /></button></div><div class="quick-facts"><div><i class="el-icon-time" /><span>年龄</span><strong>{{ ageText(pet.ageMonths) }}</strong></div><div><i class="el-icon-s-custom" /><span>性别</span><strong>{{ genderText(pet.gender) }}</strong></div><div><i class="el-icon-odometer" /><span>体重</span><strong>{{ pet.weight || '-' }} kg</strong></div></div><div class="health-chips"><span><i class="el-icon-check" /> {{ pet.vaccineStatus || '疫苗未知' }}</span><span><i class="el-icon-check" /> {{ pet.dewormStatus || '驱虫未知' }}</span><span><i class="el-icon-check" /> {{ pet.sterilizationStatus || '绝育未知' }}</span></div><div class="owner-box"><el-avatar :size="48" :src="pet.ownerAvatar">{{ (pet.ownerNickname||'主人')[0] }}</el-avatar><div><small>寄养发布人</small><strong>{{ pet.ownerNickname }}</strong></div><span>已完成身份登记</span></div><div class="detail-actions" v-if="!isOwner"><el-button type="primary" size="large" icon="el-icon-chat-dot-round" :disabled="pet.status==='OFFLINE'" @click="chatVisible=true">联系主人</el-button><el-button size="large" icon="el-icon-document-add" :disabled="pet.status!=='AVAILABLE'" @click="applyVisible=true">申请领养</el-button></div><el-alert v-else title="这是你发布的宠物，可前往个人中心管理" type="success" :closable="false" show-icon /></section></div><div class="detail-lower"><section class="content-card"><div class="content-section"><h2>关于 {{ pet.name }}</h2><div class="description-grid"><div><label>性格特点</label><p>{{ pet.personality || '暂无说明' }}</p></div><div><label>健康情况</label><p>{{ pet.healthStatus }}</p></div></div></div><div class="content-section"><h2>饲养注意事项</h2><p class="long-text">{{ pet.feedingNotes }}</p></div><div class="message-note"><i class="el-icon-chat-line-round" /><div><strong>主人寄语</strong><p>“{{ pet.ownerMessage || '希望你能认真考虑，给它一个温暖稳定的家。' }}”</p></div></div></section><aside class="safety-card"><h3><i class="el-icon-warning-outline" /> 暖心领养提醒</h3><ul><li>领养前请充分沟通并实地了解</li><li>确认家庭成员同意并做好长期规划</li><li>拒绝任何以领养为名的异常收费</li><li>领养后定期反馈宠物生活状态</li></ul></aside></div></div>
    <ChatDialog v-if="pet" v-model="chatVisible" :pet="pet" :other-id="pet.ownerId" :other-name="pet.ownerNickname" />
    <el-dialog title="提交领养申请" :visible.sync="applyVisible" width="520px"><el-alert title="请真实填写，发布人将据此认真评估" type="info" :closable="false" /><el-form ref="applyForm" :model="application" :rules="rules" label-position="top"><el-form-item label="为什么想领养它？" prop="reason"><el-input v-model.trim="application.reason" type="textarea" :rows="3" maxlength="500" show-word-limit /></el-form-item><el-form-item label="居住条件" prop="livingCondition"><el-input v-model.trim="application.livingCondition" type="textarea" :rows="3" maxlength="500" show-word-limit placeholder="住房类型、是否封窗、家庭成员意见等" /></el-form-item><el-form-item label="养宠经验" prop="experience"><el-input v-model.trim="application.experience" type="textarea" :rows="2" maxlength="500" show-word-limit /></el-form-item></el-form><span slot="footer"><el-button @click="applyVisible=false">取消</el-button><el-button type="primary" :loading="applying" @click="submitApplication">确认提交</el-button></span></el-dialog>
  </div>
</template>
<script>
import { petApi, adoptionApi } from '../api'; import ChatDialog from '../components/ChatDialog.vue'; import {petStatus,genderText,ageText,imageFallback} from '../utils/format'
export default { components:{ChatDialog}, data:()=>({pet:null,activeImage:'',loading:false,chatVisible:false,applyVisible:false,applying:false,application:{reason:'',livingCondition:'',experience:''},rules:{reason:[{required:true,message:'请填写领养原因',trigger:'blur'}],livingCondition:[{required:true,message:'请填写居住条件',trigger:'blur'}]}}), computed:{status(){return petStatus[this.pet.status]||{}},currentUser(){return JSON.parse(localStorage.getItem('pet_user')||'{}')},isOwner(){return this.currentUser.id===this.pet.ownerId}}, async created(){this.loading=true;try{this.pet=await petApi.detail(this.$route.params.id);this.activeImage=this.pet.images[0]||this.pet.coverImage}finally{this.loading=false}}, methods:{genderText,ageText,imageFallback,submitApplication(){this.$refs.applyForm.validate(async valid=>{if(!valid)return;this.applying=true;try{await adoptionApi.apply({...this.application,petId:this.pet.id});this.$message.success('领养申请已提交，请耐心等待审核');this.applyVisible=false}finally{this.applying=false}})}} }
</script>
